### ISSUE TITLE
注释内容提取到接口文档未过滤<p>标签等元素

### ISSUE THREAD

**Issue by xxm66** [wangdingfu/fudoc#2]
请求参数截图:
![image](https://user-images.githubusercontent.com/108661098/177120462-33ed71e5-4080-41d5-b279-3151ce527740.png)

生成的markdown文本截图
![image](https://user-images.githubusercontent.com/108661098/177120539-be81e344-8184-4d39-bd1e-7d275d199a61.png)

**Comment by xxm66** [comment]
注释是标准的java doc注释  提取注释内容应当按照java doc注释格式提取

**Comment by wangdingfu** [comment]
更新最新版本即可 问题已修复
