### ISSUE TITLE
生成API文档中 paramType 和项目中不一致，如 Integer 生成为 integer，XXXDTO 生成为 object 了

### ISSUE THREAD

**Issue by mythmyp** [wangdingfu/fudoc#5]

**Comment by wangdingfu** [comment]
目前生成文档中的参数类型默认进行了归类 不会直接暴露代码中实际参数类型。 其实实际编写接口文档时 正常情况也不会写实际的xxxDTO之类的类型。如果您需要展示成代码中实际的参数类型，我将会在下个版本中加入实际的参数类型, 但是需要您去修改生成文档的模板中参数类型的取值
> 如下图中为当前生成文档模板中参数类型的取值
![image](https://github.com/wangdingfu/fudoc/assets/100477650/40ca5f9d-e287-4a76-91bc-d2dd35cb5690)

预计会在这周末之前发布新的版本支持，我会在发布新的版本之后再进行回复您

此外期待您使用 **Fu Doc**的其他功能. 例如 `一键调试接口(发起http请求)`、`全局搜索api`、`一键同步文档至YApi`

> 将光标至于Controler的方法中，按下快捷键(`ALT+D`)一键发起http请求
![image](https://github.com/wangdingfu/fudoc/assets/100477650/01248444-6984-483b-a52f-05f55fa66df2)

> 在全局搜索中点击`Fu Api`或则快捷键`ALT+\` 在弹出的窗口中输入接口地址搜索接口
![image](https://github.com/wangdingfu/fudoc/assets/100477650/f4501a59-807f-4ab1-a52b-99353f57f38a)

> 将光标至于Controller的方法中, 右键`Fu Doc`--->`Sync Api` 如果没有配置YApi服务地址需要在弹出的配置页面配置地址以及将YApi项目token添加到列表中
![image](https://github.com/wangdingfu/fudoc/assets/100477650/1acdb8cc-84d5-482c-9705-278cbc3356bf)

**Comment by wangdingfu** [comment]
不好意思哈  前段时间太忙了 改好了但是没验证  一值没发版   前几天已经发版了  更新到`222.1.6.6`这个版本应该就可以了

**Comment by wangdingfu** [comment]
`222.1.6.6`这个版本目前只在idea `2022.2`以上的版本才有， 其他版本因为兼容性问题暂时还没同步. 等验证一段时间没问题之后会全部同步到idea其他版本中
