### ISSUE TITLE
点击Request请求(Controller的图表) 插件报错，无反应

### ISSUE THREAD

**Issue by 8baba** [wangdingfu/fudoc#6]
报错信息如下： while scanning for the next token found character '@' that cannot start any token. (Do not use @ for indentation)  in 'reader', line 7, column 11:         name: @artifactId@               ^  	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:470) 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:69， 
应该和我的Yaml配置有关系

**Comment by 8baba** [comment]
yaml 配置如下

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:thtf-register}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  autoconfigure:
    exclude: org.springframework.cloud.gateway.config.GatewayAutoConfiguration,org.springframework.cloud.gateway.config.GatewayClassPathWarningAutoConfiguration
  profiles:
    active: @profiles.active@

**Comment by 8baba** [comment]
![image](https://github.com/wangdingfu/fudoc/assets/49528104/e32a29e5-d5fa-4ffc-b874-b310c924e5b5)
部分显示乱码
![image](https://github.com/wangdingfu/fudoc/assets/49528104/41427ccc-1730-4811-9d67-1fef54c7a120)
showDoc配置不显示

**Comment by 8baba** [comment]
## 报错2 
![image](https://github.com/wangdingfu/fudoc/assets/49528104/ad8a5987-1ad4-4e5e-a473-585623a0a923)

**Comment by wangdingfu** [comment]
> 报错信息如下： while scanning for the next token found character '@' that cannot start any token. (Do not use @ for indentation) in 'reader', line 7, column 11: name: @Artifactid@ ^ at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:470) at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:69， 应该和我的Yaml配置有关系

这个问题是因为读取配置文件spring. profiles. active这个配置时 无法解析@profiles.active@这个环境导致的 因为需要读取server.port端口来发起请求。我今天会先暂时修复这个问题会马上发布一个新的版本 估计2天内会审核通过就可以更新新版本了

**Comment by wangdingfu** [comment]
> ![image](https://user-images.githubusercontent.com/49528104/250426145-e32a29e5-d5fa-4ffc-b874-b310c924e5b5.png) 部分显示乱码 ![image](https://user-images.githubusercontent.com/49528104/250426251-41427ccc-1730-4811-9d67-1fef54c7a120.png) showDoc配置不显示 ![image](https://user-images.githubusercontent.com/49528104/250426377-72d0970c-94dd-44f8-8ef4-374b8d47644f.png)
> 
> Idea版本2023.1 我觉得这应该是个不存的插件，可以替代fastRequest, 但是我的IDEA用不了

非常感谢你的评论和提出的问题、我会及时修复这些问题 乱码这个今天也会一起修复。 至于showdoc同步因为还未调试完毕 预计下周支持同步文档至shwodoc 目前已经支持同步文档至apifox和yapi

**Comment by wangdingfu** [comment]
> ## 报错2
> ![image](https://user-images.githubusercontent.com/49528104/250426978-ad8a5987-1ad4-4e5e-a473-585623a0a923.png)

这个问题我今天检查下，好像在222.1.6.7版本已经修复了，不过这个版本还未审核通过。

**Comment by wangdingfu** [comment]
目前插件每一个小版本的更新主要先支持idea2022.2以上的版本。当使用一段时间没问题后才会逐步支持idea其他版本。因为用的人比较少 所以覆盖的场景比较少 像以上的问题在我的电脑没有出现过 所以一直都没有浮现出来 非常感谢你的反馈可以让这个插件更加的完善。如果还有其他问题非常希望你能提供出来 我都会尽快修复这些问题的

**Comment by 8baba** [comment]
### 以下是一些小的问题
- 在String的字段上加上 @see String 报错，
![image](https://github.com/wangdingfu/fudoc/assets/49528104/f9675f33-2f42-4b15-8fef-3b5d491cc1f5)
- 我的格式是LocalDatetime类型，和String[] 的格式 示例显示可能有些问题 ,
![image](https://github.com/wangdingfu/fudoc/assets/49528104/f3463c17-9497-4cd0-b5f4-28a5559e095c)
![image](https://github.com/wangdingfu/fudoc/assets/49528104/d80fc769-76b6-4fb6-9f23-e11b90dfbab5)
- 自定义模板 我觉的可以给个参数的提示，类似于这样的问题，最好可以预览模板,类似于easyCode插件 (可以可能不太好实现，但是很实用)
![image](https://github.com/wangdingfu/fudoc/assets/49528104/03539b32-a7c4-46fd-a1dc-41c5e72df9fe)

期待作者的完善，这是个很棒的插件，但是我现在只能用导出文档的功能

**Comment by wangdingfu** [comment]
> * 可以给个参数的提

1、模板加提示的可能排期要往后面一点 因为白天在上班 晚上可能没太多时间😂 目前主要先把bug修复完毕 和showdoc同步文档这块先完成
2、字段上加@see注解 报错这个问题我今天修复下  因为目前我解析@see主要是解析枚举生成文档 没考虑后面跟String这种类型 所以解析可能会报错
3、生成示例数据的我今天处理下  方便把对象截图我看下吗 我看下对象具体的字段类型做一些处理

非常感谢反馈哈~ 我会及时处理反馈的bug， 今天会发布优化这些问题后的版本 222.1.6.8  估计两天内Jebtrains插件市场会审核通过 到时候可以更新使用http请求模块了

**Comment by 8baba** [comment]
![image](https://github.com/wangdingfu/fudoc/assets/49528104/936c6fec-b049-4b5a-843c-9086c7cf9d6e)
当注解为 @PostMapping 时   ，点击这个图标不好用，如果注解是 @PostMapping  ("/")  这样是好用的

**Comment by wangdingfu** [comment]
> ![image](https://user-images.githubusercontent.com/49528104/250733010-936c6fec-b049-4b5a-843c-9086c7cf9d6e.png) 当注解为 @PostMapping 时 ，点击这个图标不好用，如果注解是 @PostMapping ("/") 这样是好用的

好的 这个bug我现在修复下 在发一个版本

**Comment by 8baba** [comment]
![图片](https://github.com/wangdingfu/fudoc/assets/49528104/816d6fde-7ca7-4dcb-8506-32afe58073e0)
针对这种路径参数的请求方式能否优化一下
![图片](https://github.com/wangdingfu/fudoc/assets/49528104/088e5f68-3e19-4394-9770-1653a2870950)
执行前置脚本无响应
![图片](https://github.com/wangdingfu/fudoc/assets/49528104/b3a05fa2-943d-4950-baca-fa7c601128bb)
保存后再打开路径没有保存上
插件版本：222.1.6.9.02

Idea：IntelliJ IDEA 2023.1.3 (Ultimate Edition)
Build #IU-231.9161.38, built on June 20, 2023
Licensed to Daniel Rudolph
Subscription is active until January 19, 2024.
For educational use only.
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3200M
Cores: 8
Non-Bundled Plugins:
    com.wdf.api (222.1.6.9.02)

**Comment by wangdingfu** [comment]
> ![图片](https://user-images.githubusercontent.com/49528104/251180811-816d6fde-7ca7-4dcb-8506-32afe58073e0.png) 针对这种路径参数的请求方式能否优化一下 ![图片](https://user-images.githubusercontent.com/49528104/251181547-088e5f68-3e19-4394-9770-1653a2870950.png) 执行前置脚本无响应 ![图片](https://user-images.githubusercontent.com/49528104/251182358-b3a05fa2-943d-4950-baca-fa7c601128bb.png) 保存后再打开路径没有保存上 插件版本：222.1.6.9.02
> 
> Idea：IntelliJ IDEA 2023.1.3 (Ultimate Edition) Build #IU-231.9161.38, built on June 20, 2023 Licensed to Daniel Rudolph Subscription is active until January 19, 2024. For educational use only. Runtime version: 17.0.7+10-b829.16 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 11.0 GC: G1 Young Generation, G1 Old Generation Memory: 3200M Cores: 8 Non-Bundled Plugins: com.wdf.api (222.1.6.9.02)

问题已经修复了 建议更新到最新版本1.7.0 文档同步至showdoc这块也已经和发布到这个版本上了
